export const STAGES = Object.freeze({
  VALIDATING: 0,
  AUTHORIZING: 0,
  SYNCING_REPOSITORY: 1,
  RESOLVING_SOURCE: 1,
  PLANNING: 1,
  QUEUED: 2,
  WAITING_FOR_WORKER: 2,
  PREPARING_WORKSPACE: 3,
  MATERIALIZING_WORKSPACE: 3,
  PREPARING_PROJECT: 4,
  ENSURING_UNITY: 4,
  LOADING_UNITY: 5,
  RESTORING_CACHE: 5,
  RESTORING_DEPENDENCIES: 5,
  BUILDING: 6,
  VERIFYING_ARTIFACT: 7,
  VALIDATING_ARTIFACT: 7,
  UPLOADING: 7,
  PUBLISHING_ARTIFACT: 7,
  UPDATING_CACHE: 8,
  CLEANING_UP: 8,
  SUCCEEDED: 9,
});

export const STAGE_NAMES = Object.freeze({
  0: 'AUTHORIZING',
  1: 'RESOLVING_SOURCE',
  2: 'WAITING_FOR_WORKER',
  3: 'MATERIALIZING_WORKSPACE',
  4: 'ENSURING_UNITY',
  5: 'RESTORING_DEPENDENCIES',
  6: 'BUILDING',
  7: 'PUBLISHING_ARTIFACT',
  8: 'CLEANING_UP',
  9: 'SUCCEEDED',
});

export function stageName(stage) {
  return STAGE_NAMES[stage] ?? `UNKNOWN_STAGE_${stage}`;
}
